name: CI

on:
  push:
      branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.11.3'

    - name: Cache Julia packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.julia/artifacts
          ~/.julia/compiled
        key: ${{ runner.os }}-julia-${{ hashFiles('test/Project.toml', 'test/Manifest.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-

    - name: Install dependencies
      run: |
        julia --project=test -e '
          using Pkg
          Pkg.develop(path=".")
          Pkg.instantiate() '

    - name: Run tests
      run: julia --project=test -e 'using Pkg; Pkg.add("Test"); Pkg.test("MonteCarlo", coverage=true)'

    - uses: julia-actions/julia-processcoverage@v1

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}